import { CATEGORIES, DEMO_PRODUCTS, formatPrice, isOwnerConfigured, isOwner } from "./config.js?v=20260929";
import { isFirebaseConfigured, auth, db, collection, getDocs, addDoc, updateDoc, deleteDoc, doc, setDoc, serverTimestamp, onAuthStateChanged, signOut } from "./firebase-init.js";
import { escapeHtml } from "./app.js?v=20260932";
const list=document.querySelector("#product-list"),status=document.querySelector("#admin-status"),editor=document.querySelector("#product-editor"),form=document.querySelector("#product-form"),saveMessage=document.querySelector("#save-message");let products=[];
function message(text,error=false){status.textContent=text;status.classList.toggle("is-error",error)}
async function publishStarterProducts(button){if(!auth.currentUser||!isOwner(auth.currentUser.email)){message("Sign in with the owner account before publishing starter products.",true);return}if(!confirm("Publish the five prepared starter products to the live catalog? Existing products with the same names will remain unchanged."))return;button.disabled=true;message("Publishing starter products...");try{await Promise.all(DEMO_PRODUCTS.map(({id,...product})=>setDoc(doc(db,"products",id),{...product,createdAt:serverTimestamp(),updatedAt:serverTimestamp()},{merge:true})));message("Starter products published. They are now editable from this dashboard.");load()}catch{message("The starter products could not be published. Check your Firebase rules and owner sign-in.",true)}finally{button.disabled=false}}
function addStarterButton(){const newProduct=document.querySelector("#new-product");if(!newProduct||document.querySelector("#publish-starter"))return;const actions=document.createElement("div");actions.className="admin-title__actions";const button=document.createElement("button");button.type="button";button.id="publish-starter";button.className="button button--outline";button.textContent="Publish starter catalog";button.addEventListener("click",()=>publishStarterProducts(button));newProduct.before(actions);actions.append(button,newProduct)}
if(isFirebaseConfigured&&isOwnerConfigured)addStarterButton()
function openEditor(product=null){form.reset();document.querySelector("#product-id").value=product?.id||"";document.querySelector("#editor-title").textContent=product?"Edit product":"Add product";if(product){document.querySelector("#name").value=product.name||"";document.querySelector("#category").value=product.category||CATEGORIES[1];document.querySelector("#price").value=product.price||"";document.querySelector("#stock").value=product.stock||"In Stock";document.querySelector("#short-spec").value=product.shortSpec||"";document.querySelector("#description").value=product.description||"";document.querySelector("#variants").value=(product.variants||[]).join(", ");document.querySelector("#featured").checked=Boolean(product.featured);document.querySelector("#image-url").value=product.images?.[0]||""}saveMessage.textContent="";editor.hidden=false;document.querySelector("#name").focus()}
function closeEditor(){editor.hidden=true}
function render(){if(!products.length){list.innerHTML='<div class="empty-state"><h2>No products yet.</h2><p>Add your first item to start the collection.</p></div>';return}list.innerHTML=products.map(product=>`<article class="admin-row"><div><div class="admin-row__name">${escapeHtml(product.name)}</div><div class="admin-row__meta">${escapeHtml(product.category)}</div></div><div>${formatPrice(product.price)}</div><div class="admin-row__meta">${escapeHtml(product.stock||"In Stock")}</div><div class="admin-row__actions"><button data-edit="${product.id}">Edit</button><button data-delete="${product.id}">Delete</button></div></article>`).join("");document.querySelectorAll("[data-edit]").forEach(button=>button.addEventListener("click",()=>openEditor(products.find(product=>product.id===button.dataset.edit))));document.querySelectorAll("[data-delete]").forEach(button=>button.addEventListener("click",async()=>{const product=products.find(item=>item.id===button.dataset.delete);if(!confirm(`Delete ${product.name}? This cannot be undone.`))return;try{await deleteDoc(doc(db,"products",product.id));message("Product deleted.");load()}catch{message("The product could not be deleted. Please try again.",true)}}));}
async function load(){message("Loading products...");try{const snapshot=await getDocs(collection(db,"products"));products=snapshot.docs.map(item=>({id:item.id,...item.data()})).sort((a,b)=>(a.name||"").localeCompare(b.name||""));render();message(`${products.length} ${products.length===1?"product":"products"} in the catalog.`)}catch{message("The catalog could not load. Check your Firebase rules and connection.",true)}}
async function save(event){event.preventDefault();const button=form.querySelector("button[type=submit]");button.disabled=true;saveMessage.classList.remove("is-error");saveMessage.textContent="Saving product...";try{const id=document.querySelector("#product-id").value,existing=products.find(product=>product.id===id),imageUrl=document.querySelector("#image-url").value.trim(),removeImage=document.querySelector("#remove-image").checked;const images=removeImage?[]:imageUrl?[imageUrl]:existing?.images||[];const payload={name:document.querySelector("#name").value.trim(),category:document.querySelector("#category").value,price:Number(document.querySelector("#price").value),stock:document.querySelector("#stock").value,shortSpec:document.querySelector("#short-spec").value.trim(),description:document.querySelector("#description").value.trim(),variants:document.querySelector("#variants").value.split(",").map(value=>value.trim()).filter(Boolean),featured:document.querySelector("#featured").checked,images,updatedAt:serverTimestamp()};if(id)await updateDoc(doc(db,"products",id),payload);else await addDoc(collection(db,"products"),{...payload,createdAt:serverTimestamp()});saveMessage.textContent="Saved successfully.";closeEditor();load()}catch{saveMessage.textContent="The product could not be saved. Check the fields and your Firebase rules.";saveMessage.classList.add("is-error")}finally{button.disabled=false}}
if(!isFirebaseConfigured||!isOwnerConfigured){document.body.innerHTML='<main class="admin-login"><section><p class="eyebrow">Setup required</p><h1>Finish owner access.</h1><p>Add the approved owner email in <code>js/config.js</code>, then return to this page.</p><a class="button button--primary" href="index.html">Back to sign in</a></section></main>'}else{onAuthStateChanged(auth,user=>{if(!user||!isOwner(user.email)){if(user)signOut(auth);location.href="index.html";return}document.querySelector("#admin-email").textContent=user.email;load()});document.querySelector("#logout").addEventListener("click",()=>signOut(auth));document.querySelector("#new-product").addEventListener("click",()=>openEditor());document.querySelector("#close-editor").addEventListener("click",closeEditor);document.querySelector("#cancel-edit").addEventListener("click",closeEditor);form.addEventListener("submit",save)}
